### ISSUE TITLE
Failure to compile on MacOS

### ISSUE THREAD

**Issue by JujuAdams** [JujuAdams/Vinyl#4]
```
/Users/******/Documents/Repos/GMS2/gms2-project-template/gms23x template/extensions/__VinylBuildScripts/pre_run_step.sh 
System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/Users/james/Documents/Repos/GMS2/gms2-project-template/gms23x template/extensions/__VinylBuildScripts/pre_run_step.sh' with working directory '/Applications/GameMaker LTS.app/Contents/MacOS/arm64'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Igor.Command.ExecuteCommandSync(String _command, String _args, Boolean _fail_on_error, String _cwd, YYDictionary`2 _env, Boolean as_admin, String timingKey, Boolean _fQuiet)
   at Igor.Utils.ExecUserCmdStep(String fileName)
   at Igor.Utils.RunUserCmdStep(String _basename)
   at Igor.BaseTargetBuilder.PreRunStep()
   at Igor.MacBuilder.Run()
   ```

**Comment by JujuAdams** [comment]
Was a weird cursed project
